import { Product, Category } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'জামদানি শাড়ি',
    nameEn: 'Jamdani Saree',
    slug: 'jamdani-saree',
    image: 'https://images.unsplash.com/photo-1610030469983-98d58908610b?w=800&h=800&fit=crop&q=80',
    count: 156,
    description: 'ঐতিহ্যবাহী ঢাকাই জামদানি',
  },
  {
    id: '2',
    name: 'নকশী কাঁথা',
    nameEn: 'Nakshi Kantha',
    slug: 'nakshi-kantha',
    image: 'https://images.unsplash.com/photo-1584948376802-7a2468f805fb?w=800&h=800&fit=crop&q=80',
    count: 89,
    description: 'হাতে তৈরি নকশী কাঁথা',
  },
  {
    id: '3',
    name: 'মৃৎশিল্প',
    nameEn: 'Ceramic & Pottery',
    slug: 'ceramic-pottery',
    image: 'https://images.unsplash.com/photo-1565193566173-034e46a8b8c9?w=800&h=800&fit=crop&q=80',
    count: 124,
    description: 'ঐতিহ্যবাহী মাটির কাজ',
  },
  {
    id: '4',
    name: 'বাংলার মিষ্টি',
    nameEn: 'Bengali Sweets',
    slug: 'bengali-sweets',
    image: 'https://images.unsplash.com/photo-1589119908995-c6837fa14848?w=800&h=800&fit=crop&q=80',
    count: 67,
    description: 'খাঁটি বাঙালি মিষ্টি',
  },
  {
    id: '5',
    name: 'বাঁশের কাজ',
    nameEn: 'Bamboo Crafts',
    slug: 'bamboo-crafts',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&h=800&fit=crop&q=80',
    count: 78,
    description: 'হস্তশিল্পের বাঁশের পণ্য',
  },
  {
    id: '6',
    name: 'মসলিন',
    nameEn: 'Muslin Fabric',
    slug: 'muslin-fabric',
    image: 'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?w=800&h=800&fit=crop&q=80',
    count: 45,
    description: 'ঐতিহাসিক মসলিন কাপড়',
  },
  {
    id: '7',
    name: 'পিতল ও কাংসার',
    nameEn: 'Brass & Bronze',
    slug: 'brass-bronze',
    image: 'https://images.unsplash.com/photo-1578749556920-d1e2e3a506e9?w=800&h=800&fit=crop&q=80',
    count: 52,
    description: 'ঐতিহ্যবাহী ধাতব শিল্প',
  },
  {
    id: '8',
    name: 'শীতল পাটি',
    nameEn: 'Shital Pati',
    slug: 'shital-pati',
    image: 'https://images.unsplash.com/photo-1596238648689-89a9e15c6d97?w=800&h=800&fit=crop&q=80',
    count: 34,
    description: 'হাতে বোনা পাটি',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'ঐতিহ্যবাহী জামদানি শাড়ি',
    nameEn: 'Traditional Jamdani Saree',
    slug: 'traditional-jamdani-saree',
    description: 'হাতে বোনা আসল ঢাকাই জামদানি শাড়ি। সূক্ষ্ম সুতায় তৈরি, প্রতিটি নকশা অনন্য। ১০০% সুতি কাপড়, দৈর্ঘ্য ৫.৫ মিটার। সাথে ব্লাউজ পিস সহ।',
    descriptionEn: 'Handwoven authentic Dhakai Jamdani saree. Fine cotton threads, unique patterns. 100% cotton, 5.5 meters length. Includes blouse piece.',
    price: 8500,
    comparePrice: 12000,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98d58908610b?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606760265455-24783a8963f7?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98d58908610b?w=800&h=800&fit=crop',
    ],
    category: 'Jamdani Saree',
    rating: 4.9,
    reviews: 342,
    inStock: true,
    tags: ['হস্তশিল্প', 'ঐতিহ্য', 'Premium', 'ঢাকাই'],
  },
  {
    id: '2',
    name: 'নকশী কাঁথা কম্বল',
    nameEn: 'Nakshi Kantha Quilt',
    slug: 'nakshi-kantha-quilt',
    description: 'গ্রামীণ বাংলার ঐতিহ্যবাহী নকশী কাঁথা। প্রতিটি সেলাইয়ে ফুটে উঠেছে পল্লী জীবনের চিত্র। আকার: ৬০"x৮০"। ১০০% সুতি কাপড়ের তৈরি।',
    descriptionEn: 'Traditional Bengali embroidered quilt. Each stitch depicts rural life. Size: 60"x80". Made from 100% cotton fabric.',
    price: 3200,
    comparePrice: 4500,
    images: [
      'https://images.unsplash.com/photo-1584948376802-7a2468f805fb?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1584948376802-7a2468f805fb?w=800&h=800&fit=crop',
    ],
    category: 'Nakshi Kantha',
    rating: 4.8,
    reviews: 189,
    inStock: true,
    tags: ['হস্তশিল্প', 'ঘর সাজানো', 'কম্বল'],
  },
  {
    id: '3',
    name: 'মাটির কলসি সেট',
    nameEn: 'Traditional Clay Pot Set',
    slug: 'clay-pot-set',
    description: 'বাংলার গ্রামীণ মাটির তৈরি কলসি সেট। ৩টি বিভিন্ন আকারের কলসি। জল ঠান্ডা রাখার জন্য আদর্শ। পরিবেশবান্ধব ও স্বাস্থ্যকর।',
    descriptionEn: 'Rural Bengali clay pot set. 3 different sizes. Perfect for keeping water cool naturally. Eco-friendly and healthy.',
    price: 1250,
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1565193566173-034e46a8b8c9?w=800&h=800&fit=crop',
    ],
    category: 'Ceramic & Pottery',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    tags: ['মাটির কাজ', 'রান্নাঘর', 'পরিবেশবান্ধব'],
  },
  {
    id: '4',
    name: 'বাংলার রসগোল্লা',
    nameEn: 'Bengali Rosogolla',
    slug: 'bengali-rosogolla',
    description: 'নরম ও রসালো বাঙালি রসগোল্লা। প্রতিদিন তৈরি, ৫০০ গ্রাম প্যাক। খাঁটি চিনির রসে তৈরি।',
    descriptionEn: 'Soft and syrupy Bengali rosogolla. Freshly made daily, 500g pack. Made with pure sugar syrup.',
    price: 450,
    images: [
      'https://images.unsplash.com/photo-1589119908995-c6837fa14848?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1541544744-378ca6f0001e?w=800&h=800&fit=crop',
    ],
    category: 'Bengali Sweets',
    rating: 4.9,
    reviews: 567,
    inStock: true,
    tags: ['মিষ্টি', 'তাজা', 'রসগোল্লা'],
  },
  {
    id: '5',
    name: 'বাঁশের ঝুড়ি সেট',
    nameEn: 'Bamboo Basket Set',
    slug: 'bamboo-basket-set',
    description: 'হাতে তৈরি বাঁশের ঝুড়ি। ৩টি বিভিন্ন সাইজ। ফল, সবজি বা ঘর সাজানোর কাজে ব্যবহার করা যায়। টেকসই ও মজবুত।',
    descriptionEn: 'Handwoven bamboo baskets. 3 different sizes. Perfect for fruits, vegetables, or home decor. Durable and sturdy.',
    price: 890,
    images: [
      'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596238648689-89a9e15c6d97?w=800&h=800&fit=crop',
    ],
    category: 'Bamboo Crafts',
    rating: 4.6,
    reviews: 234,
    inStock: true,
    tags: ['বাঁশের কাজ', 'স্টোরেজ', 'ঘর সাজানো'],
  },
  {
    id: '6',
    name: 'মসলিন স্কার্ফ',
    nameEn: 'Muslin Scarf',
    slug: 'muslin-scarf',
    description: 'ঐতিহাসিক বাংলার মসলিন কাপড়ের স্কার্ফ। অত্যন্ত নরম ও আরামদায়ক। শ্বাসযন্ত্রের জন্য উপকারী।',
    descriptionEn: 'Historic Bengali muslin fabric scarf. Extremely soft and comfortable. Breathable fabric.',
    price: 1800,
    comparePrice: 2500,
    images: [
      'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1528458909336-e7a0adfed0a5?w=800&h=800&fit=crop',
    ],
    category: 'Muslin Fabric',
    rating: 4.8,
    reviews: 178,
    inStock: true,
    tags: ['মসলিন', 'ফ্যাশন', 'স্কার্ফ'],
  },
  {
    id: '7',
    name: 'শাপলা প্রিন্ট শাড়ি',
    nameEn: 'Shapla Print Saree',
    slug: 'shapla-print-saree',
    description: 'জাতীয় ফুল শাপলা প্রিন্টের সুন্দর শাড়ি। ১০০% সুতি, দৈর্ঘ্য ৫.৫ মিটার। ব্লাউজ পিস সহ।',
    descriptionEn: 'Beautiful saree with national flower Shapla print. 100% cotton, 5.5 meters. Includes blouse piece.',
    price: 2200,
    images: [
      'https://images.unsplash.com/photo-1606760265455-24783a8963f7?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1610030469983-98d58908610b?w=800&h=800&fit=crop',
    ],
    category: 'Jamdani Saree',
    rating: 4.7,
    reviews: 289,
    inStock: true,
    tags: ['শাপলা', 'সুতি', 'প্রিন্ট'],
  },
  {
    id: '8',
    name: 'নকশী কাঁথা ব্যাগ',
    nameEn: 'Nakshi Kantha Bag',
    slug: 'nakshi-kantha-bag',
    description: 'হাতে তৈরি নকশী কাঁথার ব্যাগ। মজবুত ও স্টাইলিশ। বিভিন্ন রঙে উপলব্ধ। দৈনন্দিন ব্যবহারের জন্য আদর্শ।',
    descriptionEn: 'Hand-embroidered Nakshi Kantha bag. Durable and stylish. Available in multiple colors. Perfect for daily use.',
    price: 650,
    images: [
      'https://images.unsplash.com/photo-1584948376802-7a2468f805fb?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544816155-12df964a45f9?w=800&h=800&fit=crop',
    ],
    category: 'Nakshi Kantha',
    rating: 4.5,
    reviews: 421,
    inStock: true,
    tags: ['ব্যাগ', 'অ্যাকসেসরিজ', 'হস্তশিল্প'],
  },
  {
    id: '9',
    name: 'পিতলের থালা সেট',
    nameEn: 'Brass Plate Set',
    slug: 'brass-plate-set',
    description: 'ঐতিহ্যবাহী পিতলের থালা সেট। ৫টি বিভিন্ন আকারের থালা। বিয়ে ও বিশেষ অনুষ্ঠানের জন্য আদর্শ।',
    descriptionEn: 'Traditional brass plate set. 5 different sizes. Perfect for weddings and special occasions.',
    price: 4500,
    comparePrice: 6000,
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578749556920-d1e2e3a506e9?w=800&h=800&fit=crop',
    ],
    category: 'Brass & Bronze',
    rating: 4.8,
    reviews: 145,
    inStock: true,
    tags: ['পিতল', 'থালা', 'বিয়ের উপহার'],
  },
  {
    id: '10',
    name: 'শীতল পাটি',
    nameEn: 'Shital Pati (Cool Mat)',
    slug: 'shital-pati',
    description: 'হাতে বোনা শীতল পাটি। গরমে আরামদায়ক ঠান্ডা অনুভূতি দেয়। আকার: ৪ ফুট x ৬ ফুট।',
    descriptionEn: 'Handwoven cool mat. Provides comfortable cooling sensation in summer. Size: 4ft x 6ft.',
    price: 2800,
    images: [
      'https://images.unsplash.com/photo-1596238648689-89a9e15c6d97?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1505693416388-33437d27cdb4?w=800&h=800&fit=crop',
    ],
    category: 'Shital Pati',
    rating: 4.6,
    reviews: 98,
    inStock: true,
    tags: ['পাটি', 'হস্তশিল্প', 'গ্রীষ্ম'],
  },
  {
    id: '11',
    name: 'মিষ্টি দই',
    nameEn: 'Sweet Doi (Yogurt)',
    slug: 'mishti-doi',
    description: 'খাঁটি বাংলার মিষ্টি দই। মাটির কলসিতে তৈরি। ৫০০ গ্রাম প্যাক।',
    descriptionEn: 'Authentic Bengali sweet yogurt. Made in clay pots. 500g pack.',
    price: 350,
    images: [
      'https://images.unsplash.com/photo-1589119908995-c6837fa14848?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1563514227147-6d2a3b67b2cd?w=800&h=800&fit=crop',
    ],
    category: 'Bengali Sweets',
    rating: 4.9,
    reviews: 432,
    inStock: true,
    tags: ['মিষ্টি', 'দই', 'তাজা'],
  },
  {
    id: '12',
    name: 'কাঁসার বাটি সেট',
    nameEn: 'Bronze Bowl Set',
    slug: 'bronze-bowl-set',
    description: 'ঐতিহ্যবাহী কাংসার বাটি। ৪টি সেট। রান্নার জন্য স্বাস্থ্যকর।',
    descriptionEn: 'Traditional bronze bowls. Set of 4. Healthy for cooking.',
    price: 3800,
    comparePrice: 5000,
    images: [
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1578749556920-d1e2e3a506e9?w=800&h=800&fit=crop',
    ],
    category: 'Brass & Bronze',
    rating: 4.7,
    reviews: 167,
    inStock: true,
    tags: ['কাংসার', 'রান্নাঘর', 'স্বাস্থ্যকর'],
  },
];

export const trendingProducts = products.slice(0, 4);
export const newArrivals = products.slice(4, 8);

export const testimonials = [
  {
    id: '1',
    author: 'ফাতেমা খাতুন',
    authorEn: 'Fatema Khatun',
    role: 'ঢাকা',
    content: 'জামদানি শাড়িটি অসাধারণ! কোয়ালিটি দেখে মুগ্ধ হয়েছি। এত সুন্দর কাজ আগে কখনো দেখিনি।',
    contentEn: 'The Jamdani saree is exceptional! Quality exceeded my expectations.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
  },
  {
    id: '2',
    author: 'আহমেদ চৌধুরী',
    authorEn: 'Ahmed Chowdhury',
    role: 'চট্টগ্রাম',
    content: 'নকশী কাঁথা কম্বলটি আমার দাদীর উপহার দিয়েছিলাম। তিনি খুব খুশি হয়েছেন।',
    contentEn: 'Gifted the Nakshi Kantha quilt to my grandmother. She was very happy.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
  },
  {
    id: '3',
    author: 'নুসরাত জাহান',
    authorEn: 'Nusrat Jahan',
    role: 'সিলেট',
    content: 'মাটির কলসিগুলো খুবই সুন্দর। গ্রীষ্মে জল ঠান্ডা রাখার জন্য দারুণ কাজ করে।',
    contentEn: 'The clay pots are beautiful. Works wonderfully for keeping water cool.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
  },
];
